# 项目相关配置
system:
  # 名称
  name: code-generator
  # 版本
  version: 4.6.0
  # 版权年份
  copyrightYear: 2021
  # 首页地址
  indexUrl: /index
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 5063
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.ricky: debug
    org.springframework: warn

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  profiles: 
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.jun.plugin.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: sqlite
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
  # 多数据源自动识别对应方言的分页 ，默认为false
  autoRuntimeDialect: true

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: 
  # 匹配链接
  urlPatterns: /system/*,/tool/*